import React from 'react'

const About = () => {
  return (
    <div>
        <div className="box-c mb-8"><div className='flex justify-center font-light text-xl text-secondary2 mt-16 mb-12 custom-underline'>ABOUT US </div></div>
        <div className='mx-28 text-secondary2'>
        In Year 2022 Hoshiarpur Forest Division recognizes an increase need for the conservation protection about a highly biodiverse region which is a treasure trove of unrivalled beauty overlooking Thana Forest and its lake and setup a Nature Awareness Camp Project at Thana Village named as Jungle Lodge Thana. It is a unique concept which traverses through the accommodation in the lake facing wooden tents overlooking Thana reservoir which offered a picturesque for the nature lovers, boating experience in the Thana Dam Lake area, Jungle safari through the rough terrain of the Thana and Dehrian forests as well as the Off-Roading experience. Hoshiarpur Forest Division started this project with the main focus to economically benefit the local communities as well as to provide employment opportunities to them. Thana village is the last village of the Punjab state and through this project it will show its presence, not only on the map of Punjab but across the map of whole India. At Jungle Lodge Thana Project, there are three lake facing wooden tents on the raised platform which offers breath taking view for the visitors. It has a fully wooden dining tent hall to relish the local cuisine. The camp offered boat ride in the lake areawhich gives a thrilling experience to the visitors. Open Jeep Jungle Safari from Thana tent site to Dehrian Forest, which is around 8 km, traverses through sand dunes and various others diverse forest ecosystem. This route is a treat for the Off-Roaders. Visitors can ride through the natural water streams, have a glimpse of the feel of forests and caves while driving through the beautiful ChirPine Forests. At Dehrian Forest visitors can have a leisure time with their family at the Dehrian Nature Park.  The nature trail near Dehrian also provides best serene of landscapes from the watch tower. The next route from Dehrian Forest to Kukanet Village is one of its own kind in the whole of India. In this route the jeep drives in the naturally flowing water stream for about 5 km. This whole route is covered with bamboo canopy and other biodiversity like several species of butterflies which adds on its beauty. Hoshiarpur Forest Division has also signed a memorandum of understanding with VFC Thana under which it is decided that 50 per cent of the earning incurred by the various activities will be spent on management of forest and rest for village development after excluding the maintenance cost as per the directives of the joint forest management committee. Today, these initiatives brace a new wave of nature awareness and responsible tourism in Hoshiarpur. It is indeed a brilliant story of ecological and enchanting planning, design and implementation that served to champion the cause of conserving its natural ecosystem. So far it has achieved significant and positive impacts on the public’s awareness and created a highly productive environment for responsible tourism.
        </div>
      </div>
  )
}

export default About